### ISSUE TITLE
'' (empty string) value should not be treated as missing translation

### ISSUE THREAD

**Issue by arnebit** [ember-intl/ember-intl#473]
Steps to reproduce problem: In any existing project, change a translation string to `''` (empty string). Observe:
>=2.17.1 "Missing translation: path.to.key" displayed where (t 'path.to.key') is used
<=2.17.0 "" (nothing displayed...)

Was the change intentional? (Unfortunately, I cannot narrow it down to any change in the two commits in between.)

- Ember Version: 2.12.0
- Ember CLI Version: 2.12.0
- Ember Intl Version: 2.17.1 and later ones
- Browser(s): multiple
- Node Version: 6

**Comment by jasonmit** [comment]
The key is not an empty string but the translation key's value is?  If so, that sounds like a bug.  I'll look into fixing this shortly.

**Comment by arnebit** [comment]
Yes, indeed, the value is empty, not the key.

![ember-intl-empty-string-value](https://cloud.githubusercontent.com/assets/15689171/24136872/4f90ab44-0e11-11e7-8214-dcbae6461960.png)

If I apply the fix from the referenced commit manually, an error is thrown [in the compute method](https://github.com/ember-intl/ember-intl/blob/111492be8527f328f92d2fbbeb83d637fffa09ae/addon/helpers/-format-base.js#L46):

```
Error: <my-project@helper:t::ember563> helper requires value attribute.
    at Class.compute (vendor.js:xxxxxx)
    at ClassBasedHelperReference.compute (vendor.js:xxxxx)
    at ClassBasedHelperReference.value (vendor.js:xxxxx)
    at EvaluatedNamedArgs.value (vendor.js:xxxxx)
    ...
```

**Comment by jasonmit** [comment]
@arnebit 2.24.1 should resolve this.  I can backport it back to 1.x if necessary.

**Comment by arnebit** [comment]
Oops, sorry, I just realized I my major version was 2 all the time, so the change occurred from **2**.17.0 to **2**.17.1. (Updated the top post.)

Unfortunately, the `t helper requires value attribute` Error is still there with 2.24.1.

**Comment by jasonmit** [comment]
Fixes in 2.24.2, thanks for pointing out the issue
